apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-1-helm
  labels:
    app: example-app-1-helm
  namespace: default
spec:
  selector:
    matchLabels:
      app: example-app-1-helm
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app-1-helm
    spec:
      containers:
      - name: example-app-1-helm
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: example-app-1-helm
