apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: example-app-1-helm
  labels:
    app: example-app-1-helm
spec:
  type: ClusterIP
  selector:
    app: example-app-1-helm
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
